"""The tree that becomes the first commit is a build product, so it is tested.

The failure that matters is a tree that looks right and is not: a build
product committed by accident (doubling the repository and letting the copy
drift), or a required file left out (a repository published without a licence
or citation metadata is a defective publication).
"""
from __future__ import annotations

import os
import sys
import zipfile

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import corpusslr                                             # noqa: E402

bpt = pytest.importorskip("tools.build_push_tree",
                          reason="tools/ is not present in this checkout")

# Every test here reads .gitignore, which a source distribution correctly does
# not package, so from an unpacked archive there is nothing to assert against.
# The builder itself refuses to run in that situation rather than emitting a
# tree with no exclusions, and that refusal is what is tested below.
pytestmark = pytest.mark.skipif(
    not os.path.exists(os.path.join(ROOT, ".gitignore")),
    reason=".gitignore is not packaged in a source distribution")


@pytest.fixture(scope="module")
def tree(tmp_path_factory):
    out = str(tmp_path_factory.mktemp("push"))
    return bpt.build(out, write_zip=True, quiet=True)


def test_every_required_file_is_in_the_tree(tree):
    """build() raises on absence, so reaching here means they are all there.

    Asserted explicitly anyway, because the list is what makes the guarantee
    and a shortened list would silently weaken it.
    """
    assert len(bpt.REQUIRED) >= 20, "the required-file list has been gutted"
    for rel in bpt.REQUIRED:
        assert os.path.exists(os.path.join(tree["root"], rel)), rel


def test_no_build_product_is_staged_for_commit(tree):
    """Each of these is regenerated by one command and is a copy of tracked
    files, so committing it would double the repository."""
    for rel in ("reviewer_package", "site", "paper/docx",
                "corpusslr_validation_data", "build_check", "dist",
                "corpusslr_reviewer_package.zip",
                "corpusslr_validation_data.zip"):
        assert not os.path.exists(os.path.join(tree["root"], rel)), rel


def test_no_version_control_data_is_copied_in(tree):
    for base, dirs, _files in os.walk(tree["root"]):
        assert ".git" not in dirs, base
        assert ".hg" not in dirs and ".svn" not in dirs, base


def test_no_cache_or_virtualenv_directory_survives(tree):
    for base, dirs, _files in os.walk(tree["root"]):
        for junk in ("__pycache__", ".pytest_cache", ".mypy_cache",
                     ".ruff_cache", ".venv"):
            assert junk not in dirs, "%s in %s" % (junk, base)


def test_the_typeset_article_is_tracked(tree):
    """Deliberate exception to the build-product rule: CI has no LaTeX, so
    ignoring the PDF would leave the repository with no readable article."""
    assert os.path.exists(os.path.join(
        tree["root"], "paper", "corpusslr_softwarex.pdf"))


def test_the_ignore_rules_come_from_the_file_not_from_a_second_list():
    """A restated list would drift from .gitignore; parsing it cannot."""
    patterns = bpt.read_ignore_patterns(ROOT)
    assert patterns, "no patterns parsed, so nothing would be excluded"
    names = {p for p, _d in patterns}
    for expected in ("site", "reviewer_package", "dist"):
        assert expected in names, sorted(names)


@pytest.mark.parametrize("rel,is_dir,ignored", [
    # anchored directory patterns, and files beneath them
    ("site", True, True),
    ("site/index.html", False, True),
    ("paper/docx", True, True),
    ("paper/docx/x.docx", False, True),
    # anchored GLOB patterns: matching only the literal prefix let every
    # LaTeX intermediate into the tree
    ("paper/corpusslr_softwarex.aux", False, True),
    ("paper/corpusslr_softwarex.bbl", False, True),
    ("paper/corpusslr_softwarex.log", False, True),
    # bare-name patterns matching any component: an earlier matcher copied
    # the whole of .mypy_cache/ and every __pycache__/ into the tree
    ("corpusslr/__pycache__/x.pyc", False, True),
    (".mypy_cache/3.10/cache.0.db", False, True),
    ("corpusslr_validation_data.zip", False, True),
    # and everything that must survive
    ("corpusslr/dedup.py", False, False),
    ("paper/corpusslr_softwarex.tex", False, False),
    ("paper/corpusslr_softwarex.pdf", False, False),
    ("paper/references.bib", False, False),
    ("validation/eval_asysd.py", False, False),
    ("validation/eval_domains_15.py", False, False),
    ("README.md", False, False),
    ("KNOWN_ISSUES.md", False, False),
])
def test_ignored_paths_are_actually_matched(rel, is_dir, ignored):
    patterns = bpt.read_ignore_patterns(ROOT)
    assert bpt.is_ignored(rel, patterns, is_dir) is ignored


def test_the_tree_carries_the_current_version(tree):
    assert tree["version"] == corpusslr.__version__


def test_the_zip_holds_one_top_level_directory(tree):
    with zipfile.ZipFile(tree["zip"]) as zf:
        tops = {n.split("/")[0] for n in zf.namelist()}
    assert tops == {bpt.TREE_DIRNAME}, tops


def test_a_tree_missing_a_required_file_is_refused(tmp_path, monkeypatch):
    """Prove the guarantee fires rather than trusting that it would."""
    monkeypatch.setattr(bpt, "REQUIRED",
                        list(bpt.REQUIRED) + ["A_FILE_THAT_IS_NOT_THERE.md"])
    with pytest.raises(SystemExit):
        bpt.build(str(tmp_path / "broken"), write_zip=False, quiet=True)


def test_the_builder_refuses_to_run_without_ignore_rules(tmp_path, monkeypatch):
    """No rules would mean no exclusions, and a tree full of build products."""
    monkeypatch.setattr(bpt, "read_ignore_patterns", lambda root: [])
    with pytest.raises(SystemExit) as excinfo:
        bpt.build(str(tmp_path / "norules"), write_zip=False, quiet=True)
    assert "ignore rules" in str(excinfo.value)
